# Generated by Django 5.2.5 on 2025-08-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='barber.inicio')),
            ],
        ),
    ]
