# Generated by Django 5.2.5 on 2025-08-13 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_imagengaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('contenido', models.TextField()),
                ('resumen', models.CharField(help_text='Resumen corto para mostrar en listados', max_length=300)),
                ('imagen_destacada', models.ImageField(help_text='Imagen principal del artículo', upload_to='blog/')),
                ('autor', models.CharField(default='Administrador', max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
                'verbose_name_plural': '10. Blog/Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Barbería', max_length=100)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('mapa_google', models.TextField(blank=True, help_text='Código iframe del mapa de Google', null=True)),
                ('horario_lunes_viernes', models.CharField(default='9:00 AM - 8:00 PM', max_length=100)),
                ('horario_sabados', models.CharField(default='9:00 AM - 6:00 PM', max_length=100)),
                ('horario_domingos', models.CharField(default='Cerrado', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': '1. Configuración de Empresa',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('descuento_porcentaje', models.PositiveIntegerField(help_text='Porcentaje de descuento')),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('imagen', models.ImageField(help_text='Imagen de la promoción', upload_to='promociones/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('codigo_promocional', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': '7. Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('descripcion_corta', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('imagen', models.ImageField(help_text='Imagen del servicio', upload_to='servicios/')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fas fa-cut)', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en la página principal')),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': '4. Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de aparición')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(help_text='Imagen principal del slider (1920x1080 recomendado)', upload_to='slider/')),
                ('boton_texto', models.CharField(default='Reservar Cita', max_length=50)),
                ('boton_enlace', models.URLField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': '2. Slider Principal',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(default='Barbero', max_length=100)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(help_text='Foto del miembro del equipo', upload_to='staff/')),
                ('experiencia_anos', models.PositiveIntegerField(default=0)),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('instagram_personal', models.URLField(blank=True, null=True)),
                ('facebook_personal', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Miembro del Staff',
                'verbose_name_plural': '5. Staff/Equipo',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Información de Contacto', 'verbose_name_plural': '9. Información de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='imagengaleria',
            options={'verbose_name': 'Imagen de Galería', 'verbose_name_plural': 'Imágenes de Galería'},
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Página de Inicio', 'verbose_name_plural': '3. Página de Inicio'},
        ),
        migrations.AlterModelOptions(
            name='quienessomos',
            options={'verbose_name': 'Quiénes Somos', 'verbose_name_plural': '8. Quiénes Somos'},
        ),
        migrations.AddField(
            model_name='inicio',
            name='anos_experiencia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inicio',
            name='clientes_satisfechos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inicio',
            name='cortes_realizados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inicio',
            name='sobre_contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inicio',
            name='sobre_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='sobre_titulo',
            field=models.CharField(default='Sobre Nosotros', max_length=200),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='historia_contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='historia_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='quienes_somos/'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='historia_titulo',
            field=models.CharField(default='Nuestra Historia', max_length=200),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='valores',
            field=models.TextField(blank=True, help_text='Separa cada valor con una nueva línea', null=True),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GaleriaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('corte', 'Corte de Cabello'), ('barba', 'Arreglo de Barba'), ('combo', 'Corte + Barba'), ('estilo', 'Peinado/Estilo'), ('otro', 'Otro')], default='corte', max_length=20)),
                ('imagen_antes', models.ImageField(help_text='Foto antes del trabajo', upload_to='galeria/')),
                ('imagen_despues', models.ImageField(help_text='Foto después del trabajo', upload_to='galeria/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_trabajo', models.DateField(auto_now_add=True)),
                ('destacado', models.BooleanField(default=False)),
                ('barbero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barber.staff')),
            ],
            options={
                'verbose_name': 'Trabajo de Galería',
                'verbose_name_plural': '6. Galería de Trabajos',
                'ordering': ['-fecha_trabajo'],
            },
        ),
    ]
