# Generated by Django 5.2.5 on 2025-08-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_blog_configuracionempresa_promocion_servicio_slider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='ConfiguracionEmpresa',
        ),
        migrations.RemoveField(
            model_name='galeriatrabajo',
            name='barbero',
        ),
        migrations.DeleteModel(
            name='Promocion',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Información de Contacto', 'verbose_name_plural': '4. Información de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='imagengaleria',
            options={'verbose_name': 'Imagen de Galería', 'verbose_name_plural': '2. Galería de Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Página de Inicio', 'verbose_name_plural': '1. Página de Inicio'},
        ),
        migrations.AlterModelOptions(
            name='quienessomos',
            options={'verbose_name': 'Quiénes Somos', 'verbose_name_plural': '3. Quiénes Somos'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='horario_domingos',
            field=models.CharField(default='Cerrado', max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='horario_lunes_viernes',
            field=models.CharField(default='9:00 AM - 8:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='horario_sabados',
            field=models.CharField(default='9:00 AM - 6:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='contacto',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='valores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GaleriaTrabajo',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
