# Generated by Django 5.2.5 on 2025-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_delete_blog_delete_configuracionempresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='titulo_principal',
        ),
        migrations.AddField(
            model_name='inicio',
            name='img_prin',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/'),
        ),
    ]
