# Generated by Django 5.2.5 on 2025-08-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_remove_inicio_titulo_principal_inicio_img_prin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='logo_navbar',
            field=models.ImageField(blank=True, help_text='Logo para el menú de navegación (.png, .jpg, .ico)', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre_empresa',
            field=models.CharField(default='Barbería', max_length=100),
        ),
    ]
