# Generated by Django 5.2.5 on 2025-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0006_contacto_logo_navbar_contacto_nombre_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='logo_navbar',
            field=models.ImageField(blank=True, help_text='Logo para el menú de navegación (recomendado: .png o .jpg, tamaño pequeño como icono)', null=True, upload_to='logos/'),
        ),
    ]
