# Generated by Django 5.2.5 on 2025-08-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0007_alter_contacto_logo_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mapa_google_link',
            field=models.URLField(blank=True, help_text='Enlace directo de Google Maps', null=True),
        ),
    ]
