# Generated by Django 5.2.5 on 2025-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0008_contacto_mapa_google_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mapa_google_link',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace directo de la ubicación en Google Maps (no el iframe)', null=True, verbose_name='Enlace directo de Google Maps'),
        ),
    ]
