# Generated by Django 5.2.5 on 2025-08-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0009_alter_contacto_mapa_google_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='anos_experiencia',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='clientes_satisfechos',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='cortes_realizados',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='sobre_imagen',
        ),
        migrations.AddField(
            model_name='inicio',
            name='about_imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/', verbose_name='Imagen About 1'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='about_imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='inicio/', verbose_name='Imagen About 2'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='about_lista',
            field=models.TextField(blank=True, null=True, verbose_name='Lista de cosas (una por línea)'),
        ),
    ]
