# Generated by Django 5.2.5 on 2025-08-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0010_remove_inicio_anos_experiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen que aparece debajo del navbar en la página de Quiénes Somos', null=True, upload_to='quienes_somos/', verbose_name='Imagen Principal (Hero)'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='quienes_somos/', verbose_name='Imagen del Contenido'),
        ),
    ]
