# Generated by Django 5.2.5 on 2025-08-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0011_quienessomos_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='posicion_imagen_principal',
            field=models.CharField(choices=[('center', 'Centro'), ('top', 'Arriba'), ('bottom', 'Abajo'), ('left', 'Izquierda'), ('right', 'Derecha'), ('top-left', 'Arriba Izquierda'), ('top-right', 'Arriba Derecha'), ('bottom-left', 'Abajo Izquierda'), ('bottom-right', 'Abajo Derecha')], default='center', help_text='Controla qué parte de la imagen se muestra cuando se recorta', max_length=20, verbose_name='Posición de la Imagen Principal'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='video_archivo',
            field=models.FileField(blank=True, help_text='Sube un archivo de video directamente (.mp4, .webm, .mov)', null=True, upload_to='videos/quienes_somos/', verbose_name='Archivo de Video'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube, Vimeo o enlace directo al video (.mp4, .webm, etc)', null=True, verbose_name='URL del Video'),
        ),
    ]
