# Generated by Django 5.2.5 on 2025-08-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0012_quienessomos_posicion_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='subtitulo',
            field=models.CharField(default='Conoce nuestra historia y pasión por la barbería', help_text='Texto que aparece debajo del título principal en el hero section', max_length=300, verbose_name='Subtítulo del Hero'),
        ),
    ]
