# Generated by Django 5.2.5 on 2025-08-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0013_quienessomos_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='video_descripcion',
            field=models.TextField(default='En nuestra barbería, cada visita es una experiencia única. Combinamos técnicas tradicionales con las últimas tendencias, creando un ambiente donde el profesionalismo se encuentra con la comodidad. Más que un corte, ofrecemos un momento de relajación y cuidado personal.', help_text='Texto descriptivo en gris claro con tipografía minimalista', verbose_name='Descripción de la Experiencia'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='video_frase_manuscrita',
            field=models.CharField(default='Donde el cuidado personal se mezcla con el buen ambiente', help_text='Frase en estilo manuscrito con color rojo metálico', max_length=300, verbose_name='Frase Manuscrita'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='video_titulo_principal',
            field=models.CharField(default='Más que una barbería, un estilo de vida', help_text='Título grande con degradado blanco a dorado', max_length=200, verbose_name='Título Principal del Video'),
        ),
    ]
