# Generated by Django 5.2.5 on 2025-08-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0014_quienessomos_video_descripcion_and_more'),
    ]

    operations = [
    ]
