# Generated by Django 5.2.5 on 2025-08-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0015_auto_20250822_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quienessomos',
            old_name='video_frase_manuscrita',
            new_name='frase_manuscrita',
        ),
        migrations.RemoveField(
            model_name='quienessomos',
            name='video_descripcion',
        ),
        migrations.RemoveField(
            model_name='quienessomos',
            name='video_titulo_principal',
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='descripcion_experiencia',
            field=models.TextField(default='En nuestra barbería, cada visita es una experiencia única. Combinamos técnicas tradicionales con las últimas tendencias, creando un ambiente donde el profesionalismo se encuentra con la comodidad. Más que un corte, ofrecemos un momento de relajación y cuidado personal.', help_text='Texto descriptivo con tipografía minimalista', verbose_name='Descripción de la Experiencia'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='titulo_elegante',
            field=models.CharField(default='Más que una barbería, un estilo de vida', help_text='Título principal con degradado blanco a dorado', max_length=200, verbose_name='Título Elegante'),
        ),
    ]
