# Generated by Django 5.2.5 on 2025-08-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0016_rename_video_frase_manuscrita_quienessomos_frase_manuscrita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='texto_superior',
            field=models.CharField(default='SINCE 2021', help_text='Texto pequeño en dorado arriba (ej: SINCE 2021)', max_length=50, verbose_name='Texto Superior'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='titulo_secundario',
            field=models.CharField(default='EXPERIENCIA Y PROFESIONALIDAD', help_text='Título en mayúsculas bold', max_length=100, verbose_name='Título Secundario'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='descripcion_experiencia',
            field=models.TextField(default="Transportándote a los 80' y 90', somos una barbería exclusiva que supera tus expectativas. Cortes de cabello impecables, tintes de primera calidad y arreglos de barba excepcionales son nuestra especialidad. ¡Experimenta la auténtica elegancia en cada visita!", help_text='Descripción larga y detallada de la experiencia', verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='frase_manuscrita',
            field=models.CharField(default='El arte se demuestra con tijeras en mano y haciendo uso de los mejores productos para quienes se acercan a nuestro salón.', help_text='Primera descripción en texto normal', max_length=300, verbose_name='Descripción Artística'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='titulo_elegante',
            field=models.CharField(default='Adam The Barber', help_text='Nombre o título principal en tipografía manuscrita', max_length=200, verbose_name='Título Principal'),
        ),
    ]
