# Generated by Django 5.2.5 on 2025-08-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0017_quienessomos_texto_superior_and_more'),
    ]

    operations = [
    ]
