# Generated by Django 5.2.5 on 2025-08-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0018_adam_style_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quienessomos',
            name='texto_superior',
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='logo_superior',
            field=models.ImageField(blank=True, help_text="Imagen/logo que aparece en la parte superior del contenido elegante (reemplaza el texto 'SINCE 2021')", null=True, upload_to='quienes_somos/logos/', verbose_name='Logo Superior'),
        ),
    ]
