# Generated by Django 5.2.5 on 2025-08-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0019_remove_quienessomos_texto_superior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='logo_superior',
            field=models.ImageField(blank=True, help_text='Imagen/logo que aparece en la parte superior del contenido elegante (reemplaza el texto \'SINCE 2021\')', null=True, upload_to='quienes_somos/logos/', verbose_name='Logo Superior'),
        ),
    ]
