# Generated by Django 5.2.5 on 2025-09-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0020_auto_20250822_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_instalacion_1',
            field=models.ImageField(blank=True, help_text='Primera imagen de las instalaciones y sillas de barbería', null=True, upload_to='quienes_somos/instalaciones/', verbose_name='Instalaciones - Imagen 1'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_instalacion_2',
            field=models.ImageField(blank=True, help_text='Segunda imagen de las instalaciones y sillas de barbería', null=True, upload_to='quienes_somos/instalaciones/', verbose_name='Instalaciones - Imagen 2'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_instalacion_3',
            field=models.ImageField(blank=True, help_text='Tercera imagen de las instalaciones y sillas de barbería', null=True, upload_to='quienes_somos/instalaciones/', verbose_name='Instalaciones - Imagen 3'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_sala_retro_1',
            field=models.ImageField(blank=True, help_text="Primera imagen de la sala retro ambientada en los 90' (billar y entretenimiento)", null=True, upload_to='quienes_somos/sala_retro/', verbose_name='Sala Retro - Imagen 1'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_sala_retro_2',
            field=models.ImageField(blank=True, help_text="Segunda imagen de la sala retro ambientada en los 90' (billar y entretenimiento)", null=True, upload_to='quienes_somos/sala_retro/', verbose_name='Sala Retro - Imagen 2'),
        ),
        migrations.AddField(
            model_name='quienessomos',
            name='imagen_sala_retro_3',
            field=models.ImageField(blank=True, help_text="Tercera imagen de la sala retro ambientada en los 90' (billar y entretenimiento)", null=True, upload_to='quienes_somos/sala_retro/', verbose_name='Sala Retro - Imagen 3'),
        ),
        migrations.AlterField(
            model_name='quienessomos',
            name='logo_superior',
            field=models.ImageField(blank=True, help_text="Imagen/logo que aparece en la parte superior del contenido elegante (reemplaza el texto 'SINCE 2021'). Tamaño recomendado: 320x320 píxeles para mejor calidad.", null=True, upload_to='quienes_somos/logos/', verbose_name='Logo Superior'),
        ),
    ]
