# Generated by Django 4.0.6 on 2025-09-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0021_quienessomos_imagen_instalacion_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Servicio')),
                ('icono', models.CharField(default='fas fa-cut', help_text='Clase del icono de FontAwesome (ej: fas fa-cut, fas fa-user-tie, fas fa-spa)', max_length=50, verbose_name='Icono FontAwesome')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': '3. Servicios',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Información de Contacto', 'verbose_name_plural': '5. Información de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='quienessomos',
            options={'verbose_name': 'Quiénes Somos', 'verbose_name_plural': '4. Quiénes Somos'},
        ),
        migrations.CreateModel(
            name='ImagenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/', verbose_name='Imagen del Servicio')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional de la imagen (alt text)', max_length=255, null=True, verbose_name='Descripción de la imagen')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden en el slider')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='barber.servicio')),
            ],
            options={
                'verbose_name': 'Imagen de Servicio',
                'verbose_name_plural': '3.1. Imágenes de Servicios',
                'ordering': ['servicio', 'orden'],
            },
        ),
    ]
