# Generated by Django 4.0.6 on 2025-09-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0022_servicio_alter_contacto_options_and_more'),
    ]

    operations = [
    ]
