# Generated by Django 4.0.6 on 2025-09-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0023_auto_20250922_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagengaleria',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='galeria/videos/', verbose_name='Archivo de video'),
        ),
        migrations.AddField(
            model_name='imagengaleria',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo o enlace directo (.mp4)', null=True, verbose_name='URL de video'),
        ),
    ]
