# Generated by Django 4.0.6 on 2025-09-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0024_imagengaleria_video_imagengaleria_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagengaleria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
