# Generated by Django 4.0.6 on 2025-10-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0025_alter_imagengaleria_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagengaleria',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Imagen de Galería', 'verbose_name_plural': '2. Galería de Imágenes'},
        ),
        migrations.AddField(
            model_name='imagengaleria',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de aparición'),
        ),
    ]
