# Generated by Django 4.0.6 on 2025-10-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0026_alter_imagengaleria_options_imagengaleria_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='imagen_fondo_hero',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero de la página de contacto', null=True, upload_to='contacto/', verbose_name='Imagen de Fondo Hero'),
        ),
    ]
